### ISSUE TITLE
FR: more formats for connect

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gixsql#24]
The docs already mention _how_ it works:

```cobol
           EXEC SQL
             CONNECT TO :DBNAME
             USER       :DBAUTH
           END-EXEC.
```

To reduce the need to adjust programs to let gixpp process them, please add the "common alternative" versions, too.

```cobol
           EXEC SQL
             CONNECT       :USERNAME
             IDENTIFIED BY :PASSWD
             AT            :DBS
             USING         :CONNECTSTRING
           END-EXEC.
```

if the `AT` is not supported yet it should be accepted and warned about.

**Comment by GitMensch** [comment]
The options to connect (partially) with the use of environment variables may/may not be done, but...

> > > The last format added is parsed, but generated wrong:
> >
>> This (in theory) passed the test but I will check again.
>
> Sounds good - using three distinct values for db, user and password ;-)

Did you found the time to recheck this format (previously the dbname was not taken over)?


Any thoughts on the idea of "if the driver part is not specified (like `pgsql://`) , then use the default specified during configure (and if there is only one driver configured use this to set the default there)"?

**Comment by mridoni** [comment]
Fixed in [v1.0.16](https://github.com/mridoni/gixsql/releases/v1.0.16)

**Comment by GitMensch** [comment]
ocesql format verified as working (citpgsql will come some days later)

**Comment by GitMensch** [comment]
Should be re-opened as the codegen is still wrong in one place (unchanged from above):

```cobol
GIXSQL*    EXEC SQL
GIXSQL*      CONNECT TO            :DBNAME
GIXSQL*              USER          :USERNAME
GIXSQL*              USING         :CONNECTSTRING
GIXSQL*              IDENTIFIED BY :PASSWD
GIXSQL*    END-EXEC.
GIXSQL     CALL "GIXSQLConnect" USING
GIXSQL         BY REFERENCE SQLCA
GIXSQL         BY REFERENCE CONNECTSTRING
GIXSQL         BY VALUE 30
GIXSQL         BY REFERENCE x"00"
GIXSQL         BY VALUE 0
GIXSQL         BY REFERENCE USERNAME
GIXSQL         BY VALUE 10
GIXSQL         BY REFERENCE PASSWD
GIXSQL         BY VALUE 50
GIXSQL     END-CALL
```
--> DBNAME is not passed to GixSQL and therefore the driver can't connect.

**Comment by mridoni** [comment]
Thanks for pointing it out, I'll check this before releasing v1.0.17, it is at this point the last item open on the list for the next release.

**Comment by GitMensch** [comment]
Nice, so if VARCHAR2 #21 is not in scope (it would be nice, if it could, of course :-) and the logging issues #82 #84 are solved in the internal repo, then it seems that iteration came to a good end.

**Comment by GitMensch** [comment]
Fixed in 1.0.17.
